version: '3.8'

services:
  backend:
    build:
      context: .   # Path to directory with Dockerfile
      dockerfile: Dockerfile
    ports:
      - "3000:3000"  # Host:Container
    env_file:
      - .env